python sniper_ranger.py ^
    --strategy break ^
    --timeframe 60 ^
    --account_risk 2.0 ^
    --each_position_risk 0.5 ^
    --target_ratio 2.0 ^
    --early_profit yes ^
    --early_rr 0.6 ^
    --trace_exit %1 ^
    --persist_data no ^
    --addtional_levels %2