pip install pandas
pip install numpy
pip install tabulate
pip install MetaTrader5
pip install slackclient
pip install psutil
pip install Flask
pip install requests
pip install ib-insync
pip install TA-Lib
pip install termcolor
pip install colorama