pip install pandas==2.2.2
pip install numpy==1.26.1
pip install tabulate
pip install MetaTrader5
pip install slackclient
pip install psutil
pip install Flask
pip install requests
pip install ib-insync
pip install TA-Lib
pip install termcolor
pip install colorama